export default {
  // 修改楼层描述
  CHANGE_FLOOR_DESCRIPTION: 'CHANGE_FLOOR_DESCRIPTION',

  // 修改进度条状态
  CHANGE_ROUTE_PROGRESS: 'CHANGE_ROUTE_PROGRESS',

  // TEST ACTION
  ACTION_SELECT: 'SELECT',
  ACTION_UPDATE: 'UPDATE',
  ACTION_DELETE: 'DELETE',
  ACTION_CREATE: 'CREATE',

  // TEST MODEL
  MODEL_ARTICLE: 'ARTICLE',
  MODEL_VIDEO: 'VIDEO',
};
